//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.CommentOnNews = new HashSet<CommentOnNew>();
        }
    
        public int ID { get; set; }
        public string News1 { get; set; }
        public string PostedBy { get; set; }
        public System.DateTime Date { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<CommentOnNew> CommentOnNews { get; set; }
        public virtual User User { get; set; }
    }
}
