//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CommentOnNews = new HashSet<CommentOnNew>();
            this.News = new HashSet<News>();
            this.ReactOnNews = new HashSet<ReactOnNew>();
        }
    
        public int ID { get; set; }
        public string UserId { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string UserType { get; set; }
    
        public virtual ICollection<CommentOnNew> CommentOnNews { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<ReactOnNew> ReactOnNews { get; set; }
    }
}
